import type { Question } from './types';

export const enA: Question[] = [
  {
    prompt: 'What is the maximum speed limit in a built-up residential area?',
    category: 'Speed Limits',
    options: ['40 km/h', '60 km/h', '80 km/h', '100 km/h'],
    correct: 1,
    explanation: 'In built-up residential areas in Rwanda, the maximum speed limit is 60 km/h unless otherwise indicated.',
  },
  {
    prompt: 'When approaching a roundabout, who has the right of way?',
    category: 'Right of Way',
    options: [
      'The vehicle entering the roundabout',
      'The vehicle already circulating in the roundabout',
      'The larger vehicle',
      'Whoever arrives first',
    ],
    correct: 1,
    explanation: 'Vehicles already inside the roundabout always have priority over those attempting to enter.',
  },
  {
    prompt: 'This sign means:',
    category: 'Warning Signs',
    options: ['Mandatory direction', 'Construction zone', 'General caution - hazard ahead', 'End of restriction'],
    correct: 2,
    explanation: 'A red triangle with an exclamation mark warns drivers of an unspecified hazard ahead. Slow down and stay alert.',
  },
  {
    prompt: 'A pedestrian is crossing at a zebra crossing with no traffic lights. You should:',
    category: 'Pedestrian Safety',
    options: [
      'Sound your horn and continue',
      'Slow down and pass behind them',
      'Stop and give way to the pedestrian',
      'Flash your headlights',
    ],
    correct: 2,
    explanation: 'At an unlit zebra crossing, drivers must come to a complete stop and let pedestrians cross safely.',
  },
  {
    prompt: 'What is the legal blood alcohol limit for drivers in Rwanda?',
    category: 'Traffic Laws',
    options: ['0.08 g/L', '0.05 g/L', '0.02 g/L', 'Zero tolerance'],
    correct: 2,
    explanation: 'The legal blood alcohol limit for drivers in Rwanda is 0.02 g/L. Always drive sober.',
  },
  {
    prompt: 'What does a solid white line on the edge of the road mean?',
    category: 'Road Markings',
    options: ['You may cross it', 'No parking zone', 'Edge of the roadway - do not cross', 'Cycle lane'],
    correct: 2,
    explanation: 'A solid white line at the edge marks the boundary of the roadway. You should not drive beyond it.',
  },
  {
    prompt: 'When are you allowed to overtake on the left?',
    category: 'Overtaking',
    options: ['Never', 'When the vehicle ahead is turning right', 'On a one-way street', 'In a residential area'],
    correct: 1,
    explanation: 'You may only overtake on the left when the vehicle ahead is signalling to turn right.',
  },
  {
    prompt: 'What does a blue circular sign with a white arrow mean?',
    category: 'Mandatory Signs',
    options: ['One-way street', 'Mandatory direction - you must go this way', 'Recommended route', 'No entry'],
    correct: 1,
    explanation: 'A blue circle with a white arrow is a mandatory sign indicating the direction you must follow.',
  },
  {
    prompt: 'What should you do when an emergency vehicle with flashing lights approaches from behind?',
    category: 'Emergency',
    options: ['Speed up', 'Stop immediately', 'Pull over to the side and let it pass', 'Flash your hazard lights'],
    correct: 2,
    explanation: 'When an emergency vehicle approaches with flashing lights, you must pull over safely and allow it to pass.',
  },
  {
    prompt: 'What is the minimum age to obtain a provisional driving license in Rwanda?',
    category: 'Licensing',
    options: ['16 years', '18 years', '21 years', '15 years'],
    correct: 1,
    explanation: 'The minimum age to apply for a provisional driving license in Rwanda is 18 years.',
  },
  {
    prompt: 'What does a red circle with a white horizontal bar mean?',
    category: 'Prohibition Signs',
    options: ['No parking', 'No entry - do not proceed', 'Stop', 'Speed limit ends'],
    correct: 1,
    explanation: 'A red circle with a white horizontal bar means "No entry" - you cannot enter this road from that direction.',
  },
  {
    prompt: 'When driving at night, when should you use your high beam headlights?',
    category: 'Night Driving',
    options: ['Always in the city', 'On unlit roads with no oncoming traffic', 'Never', 'In heavy fog'],
    correct: 1,
    explanation: 'Use high beams on unlit roads when there is no oncoming traffic. Dip them when another vehicle approaches.',
  },
  {
    prompt: 'What does a flashing yellow traffic light mean?',
    category: 'Traffic Signals',
    options: ['Stop and wait for green', 'Proceed with caution', 'Speed up to clear the intersection', 'Prepare to stop'],
    correct: 1,
    explanation: 'A flashing yellow light means proceed with caution - check for other vehicles before crossing.',
  },
  {
    prompt: 'What should you do if you miss your intended exit on a highway?',
    category: 'Driving Safety',
    options: ['Reverse back to the exit', 'Make a U-turn', 'Continue to the next exit', 'Stop on the shoulder'],
    correct: 2,
    explanation: 'If you miss your exit, never reverse or U-turn. Continue to the next exit and turn around safely.',
  },
  {
    prompt: 'What does a yellow diamond-shaped sign indicate?',
    category: 'Warning Signs',
    options: ['End of speed limit', 'Warning of potential hazard ahead', 'Mandatory action', 'No stopping'],
    correct: 1,
    explanation: 'A yellow diamond-shaped sign warns of a potential hazard ahead on the roadway.',
  },
  {
    prompt: 'How close can you park to a pedestrian crossing?',
    category: 'Parking Rules',
    options: ['5 metres', '10 metres', '15 metres', '20 metres'],
    correct: 1,
    explanation: 'You must not park within 10 metres of a pedestrian crossing to ensure clear visibility.',
  },
  {
    prompt: 'What does a white rectangular sign with black text indicate?',
    category: 'Information Signs',
    options: ['Regulatory requirement', 'Local traffic rule', 'Direction or distance information', 'Prohibition'],
    correct: 2,
    explanation: 'White rectangular signs with black text provide information such as directions or distances.',
  },
  {
    prompt: 'What should you do before reversing your vehicle?',
    category: 'Basic Manoeuvres',
    options: ['Sound the horn', 'Check mirrors and blind spots', 'Turn on hazard lights', 'Shift to neutral'],
    correct: 1,
    explanation: 'Before reversing, always check your mirrors and blind spots for pedestrians or obstacles.',
  },
  {
    prompt: 'What is the maximum speed on a highway in Rwanda?',
    category: 'Speed Limits',
    options: ['60 km/h', '80 km/h', '100 km/h', '120 km/h'],
    correct: 2,
    explanation: 'The maximum speed on Rwandan highways is 100 km/h unless otherwise posted.',
  },
  {
    prompt: 'When must you stop at a railway crossing?',
    category: 'Railway Crossings',
    options: [
      'Only if a train is coming',
      'When lights are flashing or barrier is down',
      'Never - just slow down',
      'Only at night',
    ],
    correct: 1,
    explanation:
      'You must come to a complete stop when the warning lights are flashing, the barrier is lowered, or a signal indicates a train is approaching.',
  },
];
