import type { Question } from './types';

export const enB: Question[] = [
  {
    prompt: 'What must you do at a STOP sign?',
    category: 'Prohibition Signs',
    options: [
      'Slow down and continue if clear',
      'Only stop if traffic is coming',
      'Flash headlights and continue',
      'Stop completely before the line and give way',
    ],
    correct: 3,
    explanation: 'A STOP sign requires a complete stop before the line, even if the road looks clear. Give way to all traffic before proceeding.',
  },
  {
    prompt: 'What is the minimum distance to keep from the vehicle ahead in good conditions?',
    category: 'Safe Driving',
    options: ['1 second', '2 seconds', '5 seconds', 'No distance needed'],
    correct: 1,
    explanation: 'Keep at least a 2-second gap behind the vehicle ahead in good conditions; increase it in bad weather or at speed.',
  },
  {
    prompt: 'When are you allowed to use your mobile phone while driving?',
    category: 'Traffic Laws',
    options: [
      'Never while the vehicle is moving',
      'Only at traffic lights',
      'When parked on the shoulder',
      'At low speed',
    ],
    correct: 0,
    explanation: 'It is illegal to hold or use a phone while the vehicle is moving. Park safely before using your phone.',
  },
  {
    prompt: 'What does a flashing red traffic light mean?',
    category: 'Traffic Signals',
    options: [
      'Proceed with caution',
      'Go when safe without stopping',
      'Treat as a STOP sign - come to a full stop',
      'Yield to the right',
    ],
    correct: 2,
    explanation: 'A flashing red light means the same as a STOP sign: come to a complete stop and proceed when safe.',
  },
  {
    prompt: 'What must motorcycle riders wear while on the road?',
    category: 'Motorcycle Safety',
    options: ['A reflective vest only', 'A helmet', 'Nothing is required', 'Gloves only'],
    correct: 1,
    explanation: 'Motorcycle riders must always wear a helmet when on the road.',
  },
  {
    prompt: 'What does a solid yellow line in the middle of the road mean?',
    category: 'Road Markings',
    options: [
      'Separates lanes going the same way',
      'Separates opposing traffic - do not cross',
      'A cycle lane',
      'No stopping',
    ],
    correct: 1,
    explanation: 'A solid yellow line in the centre separates traffic moving in opposite directions; you must not cross it.',
  },
  {
    prompt: 'When should you dim your headlights for oncoming traffic at night?',
    category: 'Night Driving',
    options: [
      'Before the other vehicle is in sight',
      'At least 150 m before the other vehicle',
      'Only when the other vehicle flashes',
      'Never - keep high beams on',
    ],
    correct: 1,
    explanation: 'Dim your headlights to low beam at least 150 metres before an oncoming vehicle to avoid dazzling the driver.',
  },
  {
    prompt: 'What should you do if your vehicle breaks down on the road?',
    category: 'Emergency',
    options: [
      'Leave it and walk away',
      'Block the lane and wait',
      'Flag down other drivers',
      'Move it off the road if possible and turn on hazard lights',
    ],
    correct: 3,
    explanation: 'If your vehicle breaks down, move it off the roadway if possible, turn on your hazard lights, and call for help safely.',
  },
  {
    prompt: 'When can you overtake another vehicle?',
    category: 'Overtaking',
    options: [
      'Anytime you are in a hurry',
      'Only when it is safe and permitted by road markings',
      'On a blind curve',
      'Near a pedestrian crossing',
    ],
    correct: 1,
    explanation: 'Overtake only when it is legal and safe - where markings and visibility allow. Never on a curve or near a crossing.',
  },
  {
    prompt: 'What does a solid white line in the middle of a two-lane road mean?',
    category: 'Road Markings',
    options: ['Overtaking allowed when clear', 'It is a cycle path', 'Do not cross - no overtaking', 'End of the road'],
    correct: 2,
    explanation: 'A solid white center line means no overtaking and you must not cross it.',
  },
  {
    prompt: 'What should you check before changing lanes?',
    category: 'Lane Changes',
    options: ['Mirrors and blind spot, then signal', 'Just the mirrors', 'Just signal and go', 'Sound the horn first'],
    correct: 0,
    explanation: 'Always check your mirrors and blind spot, then signal before changing lanes.',
  },
  {
    prompt: 'At a T-intersection with no signs or lights, who has priority?',
    category: 'Right of Way',
    options: [
      'Traffic turning into the road',
      'Traffic on the through road',
      'The larger vehicle',
      'Whoever honks first',
    ],
    correct: 1,
    explanation: 'At an unmarked T-intersection, traffic on the through (main) road has the right of way.',
  },
  {
    prompt: 'What does a "No Parking" sign look like?',
    category: 'Parking Rules',
    options: [
      'A blue circle with a red cross or diagonal line',
      'A yellow triangle',
      'A green square',
      'A white octagon',
    ],
    correct: 0,
    explanation: 'A blue circular sign with a red cross or diagonal bar means parking is prohibited.',
  },
  {
    prompt: 'When driving in fog, you should use:',
    category: 'Weather Driving',
    options: ['High beams', 'Parking lights only', 'No lights at all', 'Low beams or fog lights'],
    correct: 3,
    explanation: 'In fog, use low beams or fog lights so you can see without the light reflecting back into your eyes.',
  },
  {
    prompt: 'What should you do when approaching a school zone?',
    category: 'Pedestrian Safety',
    options: [
      'Slow down and watch for children',
      'Speed up to pass quickly',
      'Sound your horn continuously',
      'Overtake the traffic',
    ],
    correct: 0,
    explanation: 'Slow down near schools and watch for children who may step onto the road suddenly.',
  },
  {
    prompt: 'What does a broken (dashed) white line in the middle of the road mean?',
    category: 'Road Markings',
    options: [
      'No overtaking ever',
      'Cycle lane',
      'Pedestrian crossing',
      'Overtaking is allowed when safe',
    ],
    correct: 3,
    explanation: 'A broken (dashed) white centre line means overtaking is allowed when it is safe to do so.',
  },
  {
    prompt: 'What should you do if an ambulance approaches with siren and flashing lights?',
    category: 'Emergency',
    options: [
      'Give way and let it pass',
      'Speed up ahead of it',
      'Block the intersection',
      'Ignore it',
    ],
    correct: 0,
    explanation: 'Always give way to emergency vehicles: pull over safely and let them pass.',
  },
  {
    prompt: 'How should you signal before turning?',
    category: 'Safe Driving',
    options: [
      'Use your indicator well before the turn',
      'Just slow down',
      'Use your horn',
      'No signal is needed',
    ],
    correct: 0,
    explanation: 'Signal your intention well before turning so other road users can anticipate your move.',
  },
  {
    prompt: 'When must you wear your seatbelt?',
    category: 'Traffic Laws',
    options: [
      'Always, both driver and passengers',
      'Only on highways',
      'Only the driver',
      'Only at night',
    ],
    correct: 0,
    explanation: 'Seatbelts must be worn by the driver and all passengers at all times.',
  },
  {
    prompt: 'What does a green traffic light mean?',
    category: 'Traffic Signals',
    options: [
      'Stop and wait',
      'Prepare to stop',
      'Go - but only if the intersection is clear',
      'Yield to the right',
    ],
    correct: 2,
    explanation: 'A green light means you may go, but only after making sure the intersection is clear.',
  },
];
