import type { Question } from './types';

export const frA: Question[] = [
  {
    prompt: 'Quelle est la vitesse maximale dans une zone résidentielle?',
    category: 'Limitations de vitesse',
    options: ['40 km/h', '60 km/h', '80 km/h', '100 km/h'],
    correct: 1,
    explanation: 'Dans les zones résidentielles au Rwanda, la vitesse maximale est de 60 km/h sauf indication contraire.',
  },
  {
    prompt: "A l'approche d'un rond-point, qui a la priorité?",
    category: 'Priorité',
    options: ['Le véhicule qui entre', 'Le véhicule déjà dans le rond-point', 'Le véhicule le plus grand', 'Celui qui arrive en premier'],
    correct: 1,
    explanation: 'Les véhicules déjà engagés dans le rond-point ont toujours la priorité.',
  },
  {
    prompt: 'Ce panneau signifie:',
    category: 'Panneaux de danger',
    options: ['Direction obligatoire', 'Zone de travaux', 'Danger général - prudence', 'Fin de restriction'],
    correct: 2,
    explanation: "Un triangle rouge avec un point d'exclamation signale un danger non précisé. Ralentissez et restez attentif.",
  },
  {
    prompt: 'Un piéton traverse sur un passage piéton sans feu. Vous devez:',
    category: 'Sécurité des piétons',
    options: ['Klaxonner et continuer', 'Ralentir et passer derrière lui', "Vous arrêter et le laisser passer", 'Faire des appels de phares'],
    correct: 2,
    explanation: "Sur un passage piéton sans feu, le conducteur doit s'arrêter complètement et laisser le piéton traverser.",
  },
  {
    prompt: "Quelle est la limite légale d'alcoolémie pour les conducteurs au Rwanda?",
    category: 'Code de la route',
    options: ['0.08 g/L', '0.05 g/L', '0.02 g/L', 'Tolérance zéro'],
    correct: 2,
    explanation: 'La limite légale au Rwanda est de 0.02 g/L. Conduisez toujours sobre.',
  },
  {
    prompt: 'Que signifie une ligne blanche continue sur le bord de la route?',
    category: 'Marquages routiers',
    options: ['Vous pouvez la franchir', 'Zone de stationnement interdit', 'Limite de la chaussée - ne pas franchir', 'Piste cyclable'],
    correct: 2,
    explanation: 'Une ligne blanche continue marque la limite de la chaussée. Vous ne devez pas la franchir.',
  },
  {
    prompt: 'Quand êtes-vous autorisé à dépasser par la gauche?',
    category: 'Dépassement',
    options: ['Jamais', 'Quand le véhicule devant tourne à droite', 'Sur une voie à sens unique', 'En zone résidentielle'],
    correct: 1,
    explanation: "Vous pouvez dépasser par la gauche quand le véhicule devant vous signale qu'il tourne à droite.",
  },
  {
    prompt: 'Que signifie un panneau bleu rond avec une flèche blanche?',
    category: 'Panneaux obligatoires',
    options: ['Sens unique', 'Direction obligatoire - vous devez aller par là', 'Itinéraire conseillé', 'Sens interdit'],
    correct: 1,
    explanation: 'Un panneau bleu rond avec une flèche blanche est une obligation de direction que vous devez suivre.',
  },
  {
    prompt: "Que faire quand un véhicule d'urgence avec gyrophare approche par derrière?",
    category: 'Urgence',
    options: ['Accélérer', "S'arrêter immédiatement", 'Se ranger et le laisser passer', 'Allumer les feux de détresse'],
    correct: 2,
    explanation: "Quand un véhicule d'urgence approche, rangez-vous et laissez-le passer.",
  },
  {
    prompt: 'Quel est l\'âge minimum pour obtenir un permis provisoire au Rwanda?',
    category: 'Permis',
    options: ['16 ans', '18 ans', '21 ans', '15 ans'],
    correct: 1,
    explanation: "L'âge minimum pour demander un permis provisoire au Rwanda est 18 ans.",
  },
  {
    prompt: 'Que signifie un cercle rouge avec une barre blanche horizontale?',
    category: "Panneaux d'interdiction",
    options: ['Stationnement interdit', 'Sens interdit - ne pas entrer', 'Stop', 'Fin de limitation'],
    correct: 1,
    explanation: 'Un cercle rouge avec une barre blanche signifie "Sens interdit" - vous ne pouvez pas entrer dans cette rue.',
  },
  {
    prompt: 'Quand utiliser les feux de route la nuit?',
    category: 'Conduite de nuit',
    options: ['Toujours en ville', 'Sur route non éclairée sans trafic venant en face', 'Jamais', 'En cas de brouillard'],
    correct: 1,
    explanation: "Utilisez les feux de route sur routes non éclairées sans trafic venant en face. Baissez-les quand un véhicule approche.",
  },
  {
    prompt: 'Que signifie un feu jaune clignotant?',
    category: 'Feux de circulation',
    options: ["Arrêtez-vous et attendez le vert", 'Passez avec prudence', 'Accélérez pour traverser', 'Préparez-vous à vous arrêter'],
    correct: 1,
    explanation: "Un feu jaune clignotant signifie passez avec prudence - vérifiez qu'aucun véhicule n'arrive.",
  },
  {
    prompt: 'Que faire si vous ratez votre sortie sur une autoroute?',
    category: 'Sécurité routière',
    options: ["Reculer jusqu'à la sortie", "Faire un demi-tour", "Continuer jusqu'à la prochaine sortie", "S'arrêter sur le bas-côté"],
    correct: 2,
    explanation: "Ne reculez jamais et ne faites pas de demi-tour. Continuez jusqu'à la prochaine sortie.",
  },
  {
    prompt: 'Que signifie un panneau jaune en forme de losange?',
    category: 'Panneaux de danger',
    options: ['Fin de limitation', 'Danger potentiel à venir', 'Action obligatoire', 'Stationnement interdit'],
    correct: 1,
    explanation: 'Un panneau jaune en losange signale un danger potentiel sur la route à venir.',
  },
  {
    prompt: "À quelle distance devez-vous stationner d'un passage piéton?",
    category: 'Stationnement',
    options: ['5 mètres', '10 mètres', '15 mètres', '20 mètres'],
    correct: 1,
    explanation: "Ne stationnez pas à moins de 10 mètres d'un passage piéton pour garantir une bonne visibilité.",
  },
  {
    prompt: 'Que signifie un panneau blanc rectangulaire avec texte noir?',
    category: "Panneaux d'information",
    options: ['Obligation réglementaire', 'Règle locale', 'Direction ou distance', 'Interdiction'],
    correct: 2,
    explanation: 'Les panneaux blancs rectangulaires avec texte noir fournissent des informations comme les directions ou distances.',
  },
  {
    prompt: 'Que devez-vous faire avant de faire marche arrière?',
    category: 'Manoeuvres',
    options: ['Klaxonner', 'Vérifier les rétroviseurs et angles morts', 'Allumer les feux de détresse', 'Passer au point mort'],
    correct: 1,
    explanation: "Avant de reculer, vérifiez toujours les rétroviseurs et les angles morts pour les piétons ou obstacles.",
  },
  {
    prompt: 'Quelle est la vitesse maximale sur autoroute au Rwanda?',
    category: 'Limitations',
    options: ['60 km/h', '80 km/h', '100 km/h', '120 km/h'],
    correct: 2,
    explanation: 'La vitesse maximale sur les autoroutes rwandaises est de 100 km/h sauf indication contraire.',
  },
  {
    prompt: 'Quand devez-vous vous arrêter à un passage à niveau?',
    category: 'Passage à niveau',
    options: ['Seulement si un train arrive', 'Quand les feux clignotent ou la barrière est baissée', 'Jamais - ralentissez seulement', 'Seulement la nuit'],
    correct: 1,
    explanation: "Vous devez vous arrêter complètement quand les feux clignotent, la barrière est baissée ou un signal indique qu'un train approche.",
  },
];