import type { Question } from './types';

export const frB: Question[] = [
  {
    prompt: 'Que devez-vous faire à un panneau STOP?',
    category: "Panneaux d'interdiction",
    options: [
      "Ralentir et continuer si c'est libre",
      "S'arrêter seulement si du trafic arrive",
      'Faire des appels de phares et continuer',
      "S'arrêter complètement avant la ligne et laisser la priorité",
    ],
    correct: 3,
    explanation: "Un panneau STOP impose un arrêt complet avant la ligne, même si la route semble libre. Cédez le passage à tout le trafic avant de repartir.",
  },
  {
    prompt: 'Quelle distance devez-vous garder avec le véhicule qui précède par beau temps?',
    category: 'Sécurité routière',
    options: ['1 seconde', '2 secondes', '5 secondes', 'Aucune distance nécessaire'],
    correct: 1,
    explanation: 'Gardez au moins 2 secondes d\'écart derrière le véhicule qui précède par beau temps; augmentez en cas de mauvais temps ou à grande vitesse.',
  },
  {
    prompt: 'Quand êtes-vous autorisé à utiliser votre téléphone en conduisant?',
    category: 'Code de la route',
    options: ['Jamais pendant que le véhicule roule', 'Seulement aux feux rouges', 'Quand vous êtes garé sur le bas-côté', 'À basse vitesse'],
    correct: 0,
    explanation: 'Il est interdit de tenir ou utiliser un téléphone pendant que le véhicule roule. Garez-vous avant de l\'utiliser.',
  },
  {
    prompt: 'Que signifie un feu rouge clignotant?',
    category: 'Feux de circulation',
    options: ['Passez avec prudence', 'Passez sans vous arrêter', 'Comme un panneau STOP - arrêt complet', 'Cédez le passage à droite'],
    correct: 2,
    explanation: 'Un feu rouge clignotant équivaut à un panneau STOP: arrêt complet, puis avancez quand c\'est sûr.',
  },
  {
    prompt: 'Que doivent porter les motocyclistes sur la route?',
    category: 'Sécurité routière',
    options: ['Un gilet réfléchissant uniquement', 'Un casque', "Rien n'est obligatoire", 'Des gants uniquement'],
    correct: 1,
    explanation: 'Les motocyclistes doivent toujours porter un casque sur la route.',
  },
  {
    prompt: 'Que signifie une ligne jaune au milieu de la route?',
    category: 'Marquages routiers',
    options: ['Sépare les voies dans le même sens', 'Sépare les trafics opposés - ne pas franchir', 'Une piste cyclable', 'Stationnement interdit'],
    correct: 1,
    explanation: 'Une ligne jaune continue au centre sépare les trafics de sens opposés; ne la franchissez pas.',
  },
  {
    prompt: 'Quand devez-vous baisser les feux de route la nuit pour un véhicule venant en sens inverse?',
    category: 'Conduite de nuit',
    options: ['Avant que le véhicule soit visible', 'Au moins 150 m avant le véhicule', "Seulement quand il fait des appels de phares", 'Jamais - gardez les feux de route'],
    correct: 1,
    explanation: 'Baissez vos feux de route au moins 150 mètres avant un véhicule venant en sens inverse pour ne pas éblouir.',
  },
  {
    prompt: 'Que faire si votre véhicule tombe en panne sur la route?',
    category: 'Urgence',
    options: ['Le laisser et partir', 'Bloquer la voie et attendre', 'Faire signe aux autres conducteurs', 'Le dégager si possible et allumer les feux de détresse'],
    correct: 3,
    explanation: 'En cas de panne, dégagez le véhicule si possible, allumez les feux de détresse et appelez à l\'aide.',
  },
  {
    prompt: 'Quand pouvez-vous dépasser un autre véhicule?',
    category: 'Dépassement',
    options: ["N'importe quand si vous êtes pressé", "Seulement quand c'est sûr et autorisé par le marquage", 'Dans un virage sans visibilité', "Près d'un passage piéton"],
    correct: 1,
    explanation: 'Dépassez seulement quand c\'est légal et sûr - marquages et visibilité favorables. Jamais en virage ni près d\'un passage.',
  },
  {
    prompt: 'Que signifie une ligne blanche continue au milieu d\'une route à deux voies?',
    category: 'Marquages routiers',
    options: ['Dépassement autorisé si libre', "C'est une piste cyclable", 'Ne pas franchir - dépassement interdit', 'Fin de la route'],
    correct: 2,
    explanation: 'Une ligne blanche continue centrale interdit le dépassement et le franchissement.',
  },
  {
    prompt: 'Que devez-vous vérifier avant de changer de voie?',
    category: 'Dépassement',
    options: ["Les rétroviseurs et l'angle mort, puis clignoter", 'Seulement les rétroviseurs', 'Clignoter et avancer', 'Klaxonner d\'abord'],
    correct: 0,
    explanation: 'Vérifiez toujours les rétroviseurs et l\'angle mort, puis clignotez avant de changer de voie.',
  },
  {
    prompt: 'À une intersection en T sans panneaux ni feux, qui a la priorité?',
    category: 'Priorité',
    options: ['Le trafic qui tourne', 'Le trafic sur la route principale', 'Le véhicule le plus grand', "Celui qui klaxonne en premier"],
    correct: 1,
    explanation: 'À une intersection en T sans signalisation, le trafic sur la route principale a la priorité.',
  },
  {
    prompt: "À quoi ressemble un panneau 'Stationnement interdit'?",
    category: 'Stationnement',
    options: ['Un cercle bleu avec une croix ou une barre rouge', 'Un triangle jaune', 'Un carré vert', 'Un octogone blanc'],
    correct: 0,
    explanation: 'Un panneau rond bleu avec une croix ou une barre rouge signifie stationnement interdit.',
  },
  {
    prompt: 'En cas de brouillard, vous devez utiliser:',
    category: 'Conduite de nuit',
    options: ['Les feux de route', 'Les feux de position uniquement', 'Aucun feu', 'Les feux de croisement ou antibrouillards'],
    correct: 3,
    explanation: 'Dans le brouillard, utilisez les feux de croisement ou antibrouillards pour voir sans reflet.',
  },
  {
    prompt: "À l'approche d'une école, vous devez:",
    category: 'Sécurité des piétons',
    options: ['Ralentir et surveiller les enfants', 'Accélérer pour passer vite', 'Klaxonner continuellement', 'Dépasser le trafic'],
    correct: 0,
    explanation: 'Ralentissez près des écoles et surveillez les enfants qui pourraient surgir.',
  },
  {
    prompt: 'Que signifie une ligne blanche discontinue au milieu de la route?',
    category: 'Marquages routiers',
    options: ['Dépassement jamais autorisé', 'Piste cyclable', 'Passage piéton', 'Le dépassement est permis quand c\'est sûr'],
    correct: 3,
    explanation: 'Une ligne blanche discontinue au centre autorise le dépassement quand c\'est sûr.',
  },
  {
    prompt: 'Que faire si une ambulance approche avec sirène et gyrophare?',
    category: 'Urgence',
    options: ['Céder le passage et la laisser passer', 'Accélérer devant elle', "Bloquer l'intersection", "L'ignorer"],
    correct: 0,
    explanation: 'Cédez toujours le passage aux véhicules d\'urgence: rangez-vous et laissez-les passer.',
  },
  {
    prompt: 'Comment devez-vous signaler avant de tourner?',
    category: 'Sécurité routière',
    options: ['Utiliser le clignotant bien avant le virage', 'Ralentir simplement', 'Utiliser le klaxon', "Aucun signal n'est nécessaire"],
    correct: 0,
    explanation: 'Signalez votre intention bien avant de tourner pour que les autres usagers anticipent.',
  },
  {
    prompt: 'Quand devez-vous porter la ceinture de sécurité?',
    category: 'Code de la route',
    options: ['Toujours, conducteur et passagers', 'Seulement sur autoroute', 'Seulement le conducteur', 'Seulement la nuit'],
    correct: 0,
    explanation: 'La ceinture doit être portée par le conducteur et tous les passagers en tout temps.',
  },
  {
    prompt: 'Que signifie un feu vert?',
    category: 'Feux de circulation',
    options: ["Arrêtez-vous", 'Préparez-vous à vous arrêter', "Avancez - mais seulement si l'intersection est libre", 'Cédez le passage à droite'],
    correct: 2,
    explanation: 'Un feu vert signifie que vous pouvez avancer, mais seulement après avoir vérifié que l\'intersection est libre.',
  },
];