import type { Question } from './types';

export const rwA: Question[] = [
  {
    prompt: 'Umuvuduko ntarengwa mu gace gatuwe ni uwuhe?',
    category: 'Umuvuduko',
    options: ['40 km/h', '60 km/h', '80 km/h', '100 km/h'],
    correct: 1,
    explanation: 'Mu duce dutuwe mu Rwanda, umuvuduko ntarengwa ni 60 km/h keretse icyapa kivuze ukundi.',
  },
  {
    prompt: 'Iyo wegereye rond-point, ni nde ufite uburenganzira bwo kubanza?',
    category: 'Gutanga inzira',
    options: ['Uwinjira muri rond-point', 'Usanzwe ari muri rond-point', 'Imodoka nini', 'Uwageze mbere'],
    correct: 1,
    explanation: 'Imodoka zisanzwe ziri muri rond-point ni zo zibanza kurusha izishaka kwinjira.',
  },
  {
    prompt: 'Iki cyapa gisobanura:',
    category: 'Ibyapa biburira',
    options: ['Icyerekezo gitegetswe', 'Ahari imirimo', 'Iburira rusange - hari icyago imbere', "Iherezo ry'ikibujijwe"],
    correct: 2,
    explanation: "Mpandeshatu itukura ifite akabazo iburira umushoferi akaga kadasobanuwe kari imbere.",
  },
  {
    prompt: "Umunyamaguru ari kwambukira kuri zebra crossing nta matara ahari. Ugomba:",
    category: "Umutekano w'abanyamaguru",
    options: ['Kuvuza ihoni ugakomeza', 'Kugabanya umuvuduko ukamunyura inyuma', 'Guhagarara ukamutanga inzira', 'Kumurika amatara'],
    correct: 2,
    explanation: "Kuri zebra crossing itariho amatara, umushoferi agomba guhagarara akareka umunyamaguru akambuka neza.",
  },
  {
    prompt: "Igipimo cyemewe cy'inzoga mu maraso ku bashoferi mu Rwanda ni ikihe?",
    category: "Amategeko y'umuhanda",
    options: ['0.08 g/L', '0.05 g/L', '0.02 g/L', 'Nta nzoga na mba'],
    correct: 2,
    explanation: 'Igipimo cyemewe mu Rwanda ni 0.02 g/L. Buri gihe twara udasinze.',
  },
  {
    prompt: "Umurongo wera ukomeye uri mu nkengero z'umuhanda usobanura?",
    category: 'Ibyapa byo ku muhanda',
    options: ["Urashobora kuwambuka", "Ahantu hatabishyirwamo imodoka", "Inkengero z'umuhanda - ntukambuke", "Umuhanda w'amagare"],
    correct: 2,
    explanation: "Umurongo wera ku nkengero z'umuhanda werekana aho umuhanda urangirira. Ntugomba gutambuka.",
  },
  {
    prompt: 'Ni ryari wemerewe kurenga ibumoso?',
    category: 'Kurenga',
    options: ['Ntabwo', 'Iyo imodoka iri imbere igarukira iburyo', "Umuhanda w'urugendo rumwe", 'Mu gace gatuwe'],
    correct: 1,
    explanation: 'Ushobora kurenga ibumoso iyo imodoka iri imbere yerekanaga kugarukira iburyo.',
  },
  {
    prompt: "Icyapa cy'ubururu gifite umwambi wera gisobanura iki?",
    category: 'Ibyapa biteganyijwe',
    options: ["Umuhanda w'urugendo rumwe", 'Urenga aha - ugomba kunyura inzira yerekanywe', 'Inzira iteganijwe', 'Nta kwinjira'],
    correct: 1,
    explanation: "Uruziga rw'ubururu rufite umwambi wera ni ikimenyetso kiguhana inzira ugomba gukurikira.",
  },
  {
    prompt: "Bigenzi iki iyo imodoka y'itumanaho iri inyuma yanje irimo kumurika?",
    category: 'Itumanaho',
    options: ['Kwihuta', 'Guhagarara ako kanya', 'Kureka inzira ukayirekera', "Gukoresha amatara y'ibura"],
    correct: 2,
    explanation: "Iyo imodoka y'itumanaho igeze inyuma irimo kumurika, ugomba kuyirekera umuhanda.",
  },
  {
    prompt: "Iminsi y'amavuko ikeje wewe kubona perimi provisoire mu Rwanda?",
    category: 'Gutanga perimi',
    options: ['imyaka 16', 'imyaka 18', 'imyaka 21', 'imyaka 15'],
    correct: 1,
    explanation: 'Imyaka y\'amavuko igomba kugira ngo ubone perimi provisoire mu Rwanda ni imyaka 18.',
  },
  {
    prompt: 'Icyapa gitukura gifite umurongo wera utambitse gisobanura iki?',
    category: 'Ibyapa bibujijwe',
    options: ['Ntibishyirwamo imodoka', 'Nta kwinjira - ntukomeze', 'Hagarara', 'Umuvuduko urangiye'],
    correct: 1,
    explanation: 'Uruziga rutukura rufite umurongo wera usobanura ko nta winjira - ntabwo wemerewe kwinjira muri uwo muhanda.',
  },
  {
    prompt: 'Iyo utwaye nijoro, ni ryari ugomba gukoresha amatara arekura?',
    category: 'Kutwara nijoro',
    options: ['Buri gihe mu mujyi', 'Ku mihanda idafite amatara nta modoka ikurikiye', 'Ntabwo', 'Mu kifu gikomeye'],
    correct: 1,
    explanation: 'Koresha amatara arekura ku mihanda idafite amatara nta modoka ikurikiye. Umanure iyo modoka igeze.',
  },
  {
    prompt: "Amatara y'umuhanga y'umuhondo abaka abaka asobanura iki?",
    category: "Amatara y'umuhanda",
    options: ['Hagarara utegereze icyatsi', 'Komeza witonze', 'Wihute kugirango unyure', 'Tegura guhagarara'],
    correct: 1,
    explanation: "Amatara y'umuhondo abaka abaka asobanura komeza witonze - reba ko nta modoka mbere y'ukunyura.",
  },
  {
    prompt: "Bigenzi iki iyo wakozwe n'umuhanda uri mu nzira nyamukuru?",
    category: 'Umutekano',
    options: ['Subira inyuma kuri exit', 'Kora U-turn', 'Komeza kugera kuri exit ikurikira', 'Hagarara ku rutibi'],
    correct: 2,
    explanation: "Iyo wakozwe n'exit yawe, ntukore reverse cyangwa U-turn. Komeza kugera kuri exit ikurikira.",
  },
  {
    prompt: "Icyapa cy'umuhondo gifishije uruhu rw'ipfundo risa nka diamondi gisobanura iki?",
    category: 'Ibyapa biburira',
    options: ['Umuvuduko urangiye', 'Iburira ry\'ibyago biri imbere', 'Igikorwa gitegetswe', 'Ntihahagararwa'],
    correct: 1,
    explanation: "Icyapa cy'umuhondo gifite ishusho ya diamondi kiburira umushoferi ibyago biri imbere.",
  },
  {
    prompt: 'Ugomba guhagarara intera ingana iki uvuye aho abanyamaguru bambukira?',
    category: 'Guhagarika imodoka',
    options: ['5 metres', '10 metres', '15 metres', '20 metres'],
    correct: 1,
    explanation: "Ntugomba guhagarika imodoka hafi ya metero 10 uvuye aho abanyamaguru bambukira kugirango habe uruhu rw'irebero.",
  },
  {
    prompt: "Icyapa cy'umweru gifite inyandiko yirabura gisobanura iki?",
    category: "Ibyapa by'amakuru",
    options: ['Itegeko', "Amategeko y'agace", 'Akarere cyangwa intera', 'Icabujijwe'],
    correct: 2,
    explanation: "Ibyapa by'umweru bifite inyandiko yirabura bitanga amakuru nk'akarere cyangwa intera.",
  },
  {
    prompt: "Bigenzi iki mbere yo gusubira inyuma n'imodoka?",
    category: 'Gutwara imodoka',
    options: ['Vuza ihoni', "Reba indorerwamo n'ahantu utabona", "Koresha amatara y'ibura", 'Shyira muri neutral'],
    correct: 1,
    explanation: "Mbere yo gusubira inyuma, reba indorerwamo n'ahantu utabona kugirango urebe abantu cyangwa ibintu.",
  },
  {
    prompt: 'Umuvuduko ntarengwa mu Rwanda ku muhanda mwinshi ni uwuhe?',
    category: 'Umuvuduko',
    options: ['60 km/h', '80 km/h', '100 km/h', '120 km/h'],
    correct: 2,
    explanation: 'Umuvuduko ntarengwa ku mihanda minini mu Rwanda ni 100 km/h keretse icyapa kikavuze ukundi.',
  },
  {
    prompt: "Ni ryari ugomba guhagarara ku nzira y'igari ya moshi?",
    category: "Inzira y'igari ya moshi",
    options: ['Iyo hari igari riza gusa', 'Iyo amatara abaka cyangwa urugi ruri hasi', 'Ntabwo - gabanya umuvuduko gusa', 'Nijoro gusa'],
    correct: 1,
    explanation: "Ugomba guhagarara buri gihe iyo amatara y'iburira abaka, urugi ruri hasi, cyangwa ikimenyetso kigaragaza ko igari riza.",
  },
];
