import type { Question } from './types';

export const rwB: Question[] = [
  {
    prompt: 'Ni iki ugomba gukora ku cyapa cya STOP?',
    category: 'Ibyapa bibujijwe',
    options: ['Kugabanya umuvuduko ukomeze niba hari ubusa', 'Guhagarara gusa niba hari imodoka iza', 'Kumurika amatara ukomeze', "Guhagarara burundu mbere y'umurongo utange inzira"],
    correct: 3,
    explanation: "Icyapa cya STOP kiguhitiriza guhagarara burundu mbere y'umurongo, n'ubwo umuhanda ushobora kugaragara uri ubusa. Tanga inzira imodoka zose mbere yo gukomeza.",
  },
  {
    prompt: 'Ni intera ki ugomba kugumana n\'imodoka iri imbere mu bihe byiza?',
    category: 'Umutekano',
    options: ['Iseconda 1', 'Iseconda 2', 'Iseconda 5', 'Nta nteru ngombwa'],
    correct: 1,
    explanation: 'Guma intera ya seconda 2 byibura inyuma y\'imodoka iri imbere mu bihe byiza; wongere mu bihe bibi cyangwa ku muvuduko mwinshi.',
  },
  {
    prompt: 'Ni ryari wemerewe gukoresha telefone igihe utwaye?',
    category: "Amategeko y'umuhanda",
    options: ['Ntabwo mu gihe imodoka igenda', 'Gusa ku matara atukura', 'Iyo uhagaze ku rutibi', 'Ku muvuduko muke'],
    correct: 0,
    explanation: 'Ntibyemewe gufata cyangwa gukoresha telefone igihe imodoka igenda. Hagarika neza mbere yo gukoresha telefone.',
  },
  {
    prompt: "Amatara atukura abaka abaka asobanura iki?",
    category: "Amatara y'umuhanda",
    options: ['Komeza witonze', 'Nyura mu gihe bishoboka utahagarara', "Hagarara burundu nk'icyapa cya STOP", 'Tanga inzira iyo iburyo'],
    correct: 2,
    explanation: "Amatara atukura abaka abaka asobanura nk'icyapa cya STOP: hagarara burundu hanyuma ukomeze iyo bishyize mu mizigo.",
  },
  {
    prompt: "Ni iki ugomba kwambara igihe utwaye ipikipiki?",
    category: 'Umutekano',
    options: ['Ka njeri gusa', 'Ingofero (helmet)', 'Ntakintu kirakenewe', 'Uturindantoki gusa'],
    correct: 1,
    explanation: 'Abatwaye ipikipiki bagomba buri gihe kwambara ingofero iyo bari ku muhanda.',
  },
  {
    prompt: "Umurongo w'umuhondo hagati y'umuhanda usobanura iki?",
    category: 'Ibyapa byo ku muhanda',
    options: ['Utandukanya imodoka zose zigendana', 'Utandukanya imodoka ziza mu myerekezo itandukanye - ntuwambuke', "Umuhanda w'amagare", 'Ntihahagararwa'],
    correct: 1,
    explanation: "Umurongo w'umuhondo ukomeye hagati utandukanya imodoka zigenda mu myerekezo itandukanye; ntugomba kuwambuka.",
  },
  {
    prompt: "Ni ryari ugomba kumanura amatara ku modoka iza imbere nijoro?",
    category: 'Kutwara nijoro',
    options: ["Mbere y'uko iboneka", 'Byibura metero 150 mbere y\'uko igeze', 'Gusa iyo ikumurikiye', 'Ntabwo - komeza amatara arekura'],
    correct: 1,
    explanation: 'Mano amatara yawe byibura metero 150 mbere y\'uko imodoka iza iboneka kugirango utabahira umushoferi.',
  },
  {
    prompt: 'Bigenzi iki iyo imodoka yawe yangiritse ku muhanda?',
    category: 'Itumanaho',
    options: ['Yireke ugende', 'Hagarika mu nzira utegereze', 'Menyekanisha abandi bashoferi', 'Yikure ku muhanda nubishoboka ukoreshe amatara y\'ibura'],
    correct: 3,
    explanation: "Iyo imodoka yangiritse, yikure ku muhanda nubishoboka, ukoreshe amatara y'ibura, ukahamagara abandi.",
  },
  {
    prompt: 'Ni ryari ushobora kurenga indi modoka?',
    category: 'Kurenga',
    options: ['Igihe cyose uba wihutirwa', "Gusa iyo bishyize mu mizigo kandi byemewe n'ibyapa", "Ku muhira wotamye", "Hafi y'aho abanyamaguru bambukira"],
    correct: 1,
    explanation: "Renga gusa iyo byemewe kandi bishyize mu mizigo - aho ibyapa n'irebero bihurira. Ntanujya ku muhira cyangwa hafi y'aho bambukira.",
  },
  {
    prompt: "Umurongo wera ukomeye hagati y'umuhanda w'imirongo ibiri usobanura iki?",
    category: 'Ibyapa byo ku muhanda',
    options: ['Kurenga byemewe iyo hari ubusa', "Ni umuhanda w'amagare", 'Ntuwambuke - nta kurenga', "Iherezo ry'umuhanda"],
    correct: 2,
    explanation: "Umurongo wera ukomeye hagati usobanura nta kurenga kandi ntugomba kuwambuka.",
  },
  {
    prompt: 'Ni iki ugomba gusuzuma mbere yo guhindura umurongo?',
    category: 'Gutwara imodoka',
    options: ["Indorerwamo n'ahantu utabona, hanyuma ugerage umurongo", 'Indorerwamo gusa', 'Gusa menyesha ukanyura', 'Vuza ihoni mbere'],
    correct: 0,
    explanation: "Buri gihe reba indorerwamo n'ahantu utabona, hanyuma ugerage umurongo mbere yo guhindura.",
  },
  {
    prompt: "Ku muhanda uherereye hejuru utagira ibimenyetso, ni nde ufite uburenganzira?",
    category: 'Gutanga inzira',
    options: ['Arizinjiye mu muhanda', 'Abariko kuri muhanda nyamukuru', 'Imodoka nini', 'Uvuzaga ihoni mbere'],
    correct: 1,
    explanation: "Ku muhanda uherereye utagira ibimenyetso, imodoka ziri kuri muhanda nyamukuru ni zo zibanza.",
  },
  {
    prompt: "Icyapa cyo kudahagarika imodoka kimeze gite?",
    category: 'Guhagarika imodoka',
    options: ["Uruziga rw'ubururu rufite umusaraba utukura cyangwa umurongo utambitse", "Mpandeshatu y'umuhondo", "Kare y'icyatsi", "Octagone y'umweru"],
    correct: 0,
    explanation: "Uruziga rw'ubururu rufite umusaraba utukura cyangwa umurongo utambitse rusobanura ko guhagarika imodoka bibujijwe.",
  },
  {
    prompt: 'Iyo utwaye mu kifu, ugomba gukoresha:',
    category: 'Kutwara nijoro',
    options: ['Amatara arekura', 'Amatara make gusa', 'Nta matara na mba', 'Amatara make cyangwa amatara y\'ikifu'],
    correct: 3,
    explanation: 'Mu kifu, koresha amatara make cyangwa ay\'ikifu kugirango urebe utarushya amatara.',
  },
  {
    prompt: "Iyo ugiye hafi y'ishuri, ugomba:",
    category: "Umutekano w'abanyamaguru",
    options: ['Kugabanya umuvuduko urebe abana', 'Kwihuta kugirango unyure vuba', 'Gukomeza kuvuza ihoni', 'Kurenga izindi modoka'],
    correct: 0,
    explanation: "Gabanya umuvuduko hafi y'ishuri urebe abana bashobora kwinjira mu muhanda batunguranye.",
  },
  {
    prompt: "Umurongo wera utandukanije (amabambure) hagati y'umuhanda usobanura iki?",
    category: 'Ibyapa byo ku muhanda',
    options: ['Nta kurenga na rimwe', "Umuhanda w'amagare", 'Aho abanyamaguru bambukira', 'Kurenga byemewe iyo bishyize mu mizigo'],
    correct: 3,
    explanation: 'Umurongo wera utandukanije hagati usobanura ko kurenga byemewe iyo bishyize mu mizigo.',
  },
  {
    prompt: 'Bigenzi iki iyo ambulance igeze irimo kurira ikumurika?',
    category: 'Itumanaho',
    options: ['Yitandukanya uyirekere', 'Kwihuta uyirangire imbere', 'Guhagarika indimburanyana', 'Kuyitaho'],
    correct: 0,
    explanation: 'Buri gihe tanga inzira imodoka z\'itumanaho: ikorane ku ruhande uyirekere.',
  },
  {
    prompt: 'Ni gute ugomba kumenyesha mbere yo guhindukira?',
    category: 'Gutwara imodoka',
    options: ["Gukoresha amatara y'icyerekezo mbere y'aho ugiye guhindukira", 'Kugabanya umuvuduko gusa', 'Gukoresha ihoni', 'Nta bukenewe'],
    correct: 0,
    explanation: 'Menyesha uwo ukomeza kure mbere yo guhindukira kugirango abandi barebe icyo ugomba gukora.',
  },
  {
    prompt: "Ni ryari ugomba kumenya umukandara w'umutekano?",
    category: "Amategeko y'umuhanda",
    options: ['Buri gihe, umushoferi n\'abagenzi', 'Ku mihanda minini gusa', 'Umushoferi gusa', 'Nijoro gusa'],
    correct: 0,
    explanation: "Umukandara w'umutekano ugomba kwambrawa n'umushoferi n'abagenzi bose buri gihe.",
  },
  {
    prompt: "Amatara y'icyatsi asobanura iki?",
    category: "Amatara y'umuhanda",
    options: ['Hagarara utegereze', 'Tegura guhagarara', 'Komeza - ariko gusa iyo indimburanyana iri ubusa', 'Tanga inzira iyo iburyo'],
    correct: 2,
    explanation: "Amatara y'icyatsi avuga ko ushobora komeza, ariko nyuma yo gusuzuma ko indimburanyana iri ubusa.",
  },
];
